language: ruby
bundler_args: --without development

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.15.0

matrix:
  exclude:
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4.2.gemfile

services:
  - mongodb

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
