language: ruby
bundler_args: --without development

matrix:
  include:
    - name: "Rails 4.2 on Ruby 2.3.8"
      rvm: 2.3.8
      gemfile: gemfiles/rails_4.2.gemfile

    - name: "Rails 5.0 on Ruby 2.4.10"
      rvm: 2.4.10
      gemfile: gemfiles/rails_5.0.gemfile
    - name: "Rails 5.1 on Ruby 2.4.10"
      rvm: 2.4.10
      gemfile: gemfiles/rails_5.1.gemfile
    - name: "Rails 5.2 on Ruby 2.4.10"
      rvm: 2.4.10
      gemfile: gemfiles/rails_5.2.gemfile

    - name: "Rails 5.0 on Ruby 2.5.8"
      rvm: 2.5.8
      gemfile: gemfiles/rails_5.0.gemfile
    - name: "Rails 5.1 on Ruby 2.5.8"
      rvm: 2.5.8
      gemfile: gemfiles/rails_5.1.gemfile
    - name: "Rails 5.2 on Ruby 2.5.8"
      rvm: 2.5.8
      gemfile: gemfiles/rails_5.2.gemfile

    - name: "Rails 5.2 on Ruby 2.6.6"
      rvm: 2.6.6
      gemfile: gemfiles/rails_5.2.gemfile
    - name: "Rails 6.0 on Ruby 2.6.6"
      rvm: 2.6.6
      gemfile: gemfiles/rails_6.0.gemfile

    - name: "Rails 6.0 on Ruby 2.7.1"
      rvm: 2.7.1
      gemfile: gemfiles/rails_6.0.gemfile

    - name: "Rails 4.2 on JRuby 9.1.17.0"
      rvm: jruby-9.1.17.0
      gemfile: gemfiles/rails_4.2.gemfile

    - name: "Rails 5.1 on JRuby jruby-9.2.11.1"
      rvm: jruby-9.2.11.1
      gemfile: gemfiles/rails_5.1.gemfile
    - name: "Rails 5.2 on JRuby jruby-9.2.11.1"
      rvm: jruby-9.2.11.1
      gemfile: gemfiles/rails_5.2.gemfile
    - name: "Rails 6.0 on Ruby 2.7.1"
      rvm: jruby-9.2.11.1
      gemfile: gemfiles/rails_6.0.gemfile

  allow_failures:
    - rvm: jruby-9.1.17.0
    - rvm: jruby-9.2.11.1

jdk:
- openjdk10

services:
- mongodb

# Gitter integration
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

sudo: false
